server:
  #端口号
  port: 8080
dubbo:
  application:
    name: swrd
    id: swrd
  registry:
    id: swrd_zk
    address: zookeeper://dev01-zk-mall1.secoolocal.com:2181?backup=dev01-zk-mall2.secoolocal.com:2181,dev01-zk-mall3.secoolocal.com:2181
  scan:
    basePackages: designpatterns;designpatterns.*
  provider:
    timeout: 1000
    threadpool: fixed
    threads: 300
    dispatcher: message
  protocol:
    id: dubbo
    name: dubbo
    port: 30900


---
mybatis:
  type-aliases-package: com.secoo.mall.price.dao.mysql.po
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

---
spring:
  shardingsphere:
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: erp-master
      name: ds_ms
      slave-data-source-names: erp-slave
    datasource:
      names: erp-master,erp-slave
      erp-master:
        driver-class-name: com.mysql.jdbc.Driver
        password: B6BRaCBErrOMvxDRKpRo
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://dev01-secooErpDB.master.com:3306/secooErpDB?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&socketTimeout=30000&connectTimeout=3000
        username: kaifaDB_W
      erp-slave:
        driver-class-name: com.mysql.jdbc.Driver
        password: B6BRaCBErrOMvxDRKpRo
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://dev01-secooErpDB.slave.com:3306/secooErpDB?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&socketTimeout=30000&connectTimeout=3000
        username: kaifaDB_W


---
spring:
  redis:
    #两种方式（二选一）：1、单实例 2、集群
    #    host: 10.0.253.9
    #    port: 6379
    cluster:
      #nodes: 10.0.9.100:6379,10.0.9.101:6379,10.0.9.102:6379
      nodes: dev01-rediscluster01.secoolocal.com:7001,dev01-rediscluster01.secoolocal.com:7002,dev01-rediscluster02.secoolocal.com:7001,dev01-rediscluster02.secoolocal.com:7002,dev01-rediscluster03.secoolocal.com:7001,dev01-rediscluster03.secoolocal.com:7002
    #password: helloworld
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    #database: 0
    # 连接超时时间（毫秒)
    timeout: 1000ms
    # redis client配置，使用lettuce
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 2
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1000ms
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 16
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8



